-- CreateEnum
CREATE TYPE "DOCTOR_VERIFICATION_STATUS" AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');

-- AlterTable
ALTER TABLE "doctors" ADD COLUMN     "verification_status" "DOCTOR_VERIFICATION_STATUS" NOT NULL DEFAULT 'PENDING';
