// Hero Section
export const CONFIG_HERO_TITLE_TEXT = "HERO_TITLE_TEXT";
export const CONFIG_HERO_SUBTITLE_TEXT = "HERO_SUBTITLE_TEXT";
export const CONFIG_HERO_IMAGE = "HERO_IMAGE";
export const CONFIG_HERO_REVIEW = "HERO_REVIEW";
export const CONFIG_FEATURED_DOCTOR = "FEATURED_DOCTOR";

// About Section
export const CONFIG_ABOUT_TEXT = "ABOUT_TEXT";
export const CONFIG_ABOUT_LIST = "ABOUT_LIST";
export const CONFIG_OPENING_HOURS = "OPENING_HOURS";

// Featured Services
export const CONFIG_FEATURED_SERVICES = "FEATURED_SERVICES";

// Featured Specialties
export const CONFIG_FEATURED_SPECIALTIES = "FEATURED_SPECIALTIES";

// Testimonial Section
export const CONFIG_TESTIMONIAL_IMAGE = "TESTIMONIAL_IMAGE";

// President Section
export const CONFIG_PRESIDENT_IMAGE = "PRESIDENT_IMAGE";
export const CONFIG_PRESIDENT_NAME = "PRESIDENT_NAME";
export const CONFIG_PRESIDENT_TEXT = "PRESIDENT_TEXT";
export const CONFIG_PRESIDENT_POSITION = "PRESIDENT_POSITION";
export const CONFIG_PRESIDENT_EXPERIENCE = "PRESIDENT_EXPERIENCE";
export const CONFIG_PRESIDENT_SKILLS = "PRESIDENT_SKILLS";

// FAQ
export const CONFIG_FAQ_ITEMS = "FAQ_ITEMS";

// Footer
export const CONFIG_FOOTER_TEXT = "FOOTER_TEXT";

// Contact
export const CONFIG_CONTACT_EMAIL = "CONTACT_EMAIL";
export const CONFIG_SUPPORT_EMAIL = "SUPPORT_EMAIL";
export const CONFIG_CONTACT_PHONE = "CONTACT_PHONE";
export const CONFIG_SOCIAL_LINKS = "SOCIAL_LINKS";
